name: React CD

on: 
  push: 
    branches: [main]

jobs:
  deploy:
    name: React Deploy job
    runs-on: ubuntu-latest

    steps:
      - name: Copy all repo
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v3
        with: 
          node-version: 20

      - name: Install depedencies
        run: npm install

      - name: Run build
        run: npm run build
  
      - name: Install vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN_REACT }} --yes
  
